name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord of Commit(s)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMITS=$(jq -c '.commits[]' $GITHUB_EVENT_PATH | head -n 5)
          FIELDS=""

          while IFS= read -r commit; do
            SHA=$(echo $commit | jq -r '.id' | cut -c1-7)
            URL=$(echo $commit | jq -r '.url')
            MESSAGE=$(echo $commit | jq -r '.message' | head -c 200)
            AUTHOR=$(echo $commit | jq -r '.author.name')

            FIELDS="$FIELDS,
              {
                \"name\": \"[$SHA] $AUTHOR\",
                \"value\": \"[$MESSAGE]($URL)\"
              }"
          done <<< "$COMMITS"

          FIELDS=${FIELDS#,}  # Remove leading comma

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"GitHub Actions\",
              \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
              \"embeds\": [{
                \"title\": \"📦 New Commit(s) Pushed\",
                \"description\": \"**Repository:** [${{ github.repository }}](https://github.com/${{ github.repository }})\n**Branch:** \`${{ github.ref_name }}\`\n**Pushed by:** ${{ github.actor }}\",
                \"fields\": [$FIELDS],
                \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",
                \"color\": 7506394
              }]
            }" \
            $DISCORD_WEBHOOK
