name: Discord Notify on Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send commits to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ACTOR: ${{ github.actor }}
          BRANCH: ${{ github.ref_name }}
        run: |
          if ! jq -e '.commits | length > 0' "$GITHUB_EVENT_PATH" > /dev/null; then
            echo "No commits to report"
            exit 0
          fi

          EMBEDS=""
          i=0

          jq -c '.commits[]' "$GITHUB_EVENT_PATH" | while read -r COMMIT; do
            i=$((i+1))
            if [ "$i" -gt 5 ]; then
              break
            fi

            SHA=$(echo "$COMMIT" | jq -r '.id' | cut -c1-7)
            URL=$(echo "$COMMIT" | jq -r '.url')
            MSG=$(echo "$COMMIT" | jq -r '.message' | head -c 200)
            AUTHOR=$(echo "$COMMIT" | jq -r '.author.name')

            EMBEDS="$EMBEDS,
              {
                \"title\": \"[api:$BRANCH] 1 new commit\",
                \"description\": \"[$SHA]($URL) $MSG - $AUTHOR\",
                \"color\": 7506394
              }"
          done

          EMBEDS="[${EMBEDS#,}]" # Remove leading comma

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"$ACTOR\",
              \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
              \"embeds\": $EMBEDS
            }" \
            "$DISCORD_WEBHOOK"
